# Visualization Quality Control

Set of useful functions for calculating various measures from data and visualizing them.

## Installation

### Dependencies

Note that before installing, you will want to install the `ggbiplot` package, and at least `v1.2.1` of the `ComplexHeatmap` package. Robert M Flight maintains a fork of `ggbiplot` on GitHub because it is not part of CRAN, and as of July 2, 2015, `ComplexHeatmap` must be installed from GitHub:

```r
devtools::install_github("rmflight/ggbiplot")
devtools::install_github("jokergoo/ComplexHeatmap")
```

Other odd dependencies that may not be present include the `dendsort` package, and
the `viridis` package:

```r
install.packages("dendsort")
install.packages("viridis")
```

### This Package

This package can be installed by cloning from the GitLab repo:

```r
git clone https://gitlab.cesb.uky.edu/rmflight/visualizationQualityControl.git
cd visualizationQualityControl
R
devtools::install(".", quick = FALSE) # builds the vignette, which you definitely want
```

## Open Vignette

To open the vignette giving an example of examining data for quality control
purposes, you should see the `quality_control` vignette using:

```r
vignette("quality_control", package = "visualizationQualityControl")
```

This will open the vignette in the help pane in `RStudio`, which is often what
you want to happen.

## Fake Data Generation

Some fake data is stored in `grp_cor_data` that is useful for testing the `median_correlation`
function. It was generated by:

```r
library(fakeDataWithError)
set.seed(1234)

s1 <- runif(100, 0, 1)
grp1 <- add_uniform_noise(10, s1, 0.1)

model_data <- data.frame(s1 = s1, s2 = grp1[, 1])

lm_1 <- lm(s1 ~ s2, data = model_data)

lm_1$coefficients[2] <- 0.5

s3 <- predict(lm_1)
s4 <- add_uniform_noise(1, s3, 0.2)

grp2 <- add_uniform_noise(10, s4, 0.1)

grp_class <- rep(c("grp1", "grp2"), each = 10)

grp_cor_data <- list(data = cbind(grp1, grp2), class = grp_class)
```

